# Generated by Django 2.0.1 on 2018-01-30 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FAQDatabase',
        ),
    ]
