# Generated by Django 2.0.1 on 2018-02-01 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='posted_by',
            field=models.CharField(default='Admin', max_length=100),
        ),
    ]
