# Generated by Django 2.0.1 on 2018-01-30 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FAQ',
        ),
    ]
