# Generated by Django 2.0.1 on 2018-01-30 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0002_delete_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQDatabase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=140)),
                ('answer', models.CharField(max_length=240)),
            ],
        ),
    ]
